<?php
/**
 * CalendarDay
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;

use \ArrayAccess;
use \MtnManager\ObjectSerializer;

/**
 * CalendarDay Class Doc Comment
 *
 * @category Class
 * @description Operating hours for a specific calendar date.   Represents the calculated open/close times for a single day, combining  information from recurring schedules and any single-day overrides.
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CalendarDay implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CalendarDay';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'date' => '\DateTime',
        'day_of_week' => '\MtnManager\Model\DayOfWeek',
        'is_open' => 'bool',
        'opens_at' => 'string',
        'closes_at' => 'string',
        'closure_reason' => '\MtnManager\Model\ClosureReason',
        'special_event' => 'string',
        'amenities' => '\MtnManager\Model\AmenityCalendarEntry[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'date' => 'date',
        'day_of_week' => null,
        'is_open' => null,
        'opens_at' => null,
        'closes_at' => null,
        'closure_reason' => null,
        'special_event' => null,
        'amenities' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'date' => false,
        'day_of_week' => false,
        'is_open' => false,
        'opens_at' => true,
        'closes_at' => true,
        'closure_reason' => true,
        'special_event' => true,
        'amenities' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date' => 'date',
        'day_of_week' => 'day_of_week',
        'is_open' => 'is_open',
        'opens_at' => 'opens_at',
        'closes_at' => 'closes_at',
        'closure_reason' => 'closure_reason',
        'special_event' => 'special_event',
        'amenities' => 'amenities'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date' => 'setDate',
        'day_of_week' => 'setDayOfWeek',
        'is_open' => 'setIsOpen',
        'opens_at' => 'setOpensAt',
        'closes_at' => 'setClosesAt',
        'closure_reason' => 'setClosureReason',
        'special_event' => 'setSpecialEvent',
        'amenities' => 'setAmenities'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date' => 'getDate',
        'day_of_week' => 'getDayOfWeek',
        'is_open' => 'getIsOpen',
        'opens_at' => 'getOpensAt',
        'closes_at' => 'getClosesAt',
        'closure_reason' => 'getClosureReason',
        'special_event' => 'getSpecialEvent',
        'amenities' => 'getAmenities'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('day_of_week', $data ?? [], null);
        $this->setIfExists('is_open', $data ?? [], null);
        $this->setIfExists('opens_at', $data ?? [], null);
        $this->setIfExists('closes_at', $data ?? [], null);
        $this->setIfExists('closure_reason', $data ?? [], null);
        $this->setIfExists('special_event', $data ?? [], null);
        $this->setIfExists('amenities', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ($this->container['day_of_week'] === null) {
            $invalidProperties[] = "'day_of_week' can't be null";
        }
        if ($this->container['is_open'] === null) {
            $invalidProperties[] = "'is_open' can't be null";
        }
        if (!is_null($this->container['opens_at']) && !preg_match("/^([01]\\d|2[0-3]):[0-5]\\d$/", $this->container['opens_at'])) {
            $invalidProperties[] = "invalid value for 'opens_at', must be conform to the pattern /^([01]\\d|2[0-3]):[0-5]\\d$/.";
        }

        if (!is_null($this->container['closes_at']) && !preg_match("/^([01]\\d|2[0-3]):[0-5]\\d$/", $this->container['closes_at'])) {
            $invalidProperties[] = "invalid value for 'closes_at', must be conform to the pattern /^([01]\\d|2[0-3]):[0-5]\\d$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime $date Calendar date (YYYY-MM-DD).
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets day_of_week
     *
     * @return \MtnManager\Model\DayOfWeek
     */
    public function getDayOfWeek()
    {
        return $this->container['day_of_week'];
    }

    /**
     * Sets day_of_week
     *
     * @param \MtnManager\Model\DayOfWeek $day_of_week Day of the week.
     *
     * @return self
     */
    public function setDayOfWeek($day_of_week)
    {
        if (is_null($day_of_week)) {
            throw new \InvalidArgumentException('non-nullable day_of_week cannot be null');
        }
        $this->container['day_of_week'] = $day_of_week;

        return $this;
    }

    /**
     * Gets is_open
     *
     * @return bool
     */
    public function getIsOpen()
    {
        return $this->container['is_open'];
    }

    /**
     * Sets is_open
     *
     * @param bool $is_open Whether the resort is open on this day.
     *
     * @return self
     */
    public function setIsOpen($is_open)
    {
        if (is_null($is_open)) {
            throw new \InvalidArgumentException('non-nullable is_open cannot be null');
        }
        $this->container['is_open'] = $is_open;

        return $this;
    }

    /**
     * Gets opens_at
     *
     * @return string|null
     */
    public function getOpensAt()
    {
        return $this->container['opens_at'];
    }

    /**
     * Sets opens_at
     *
     * @param string|null $opens_at Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
     *
     * @return self
     */
    public function setOpensAt($opens_at)
    {
        if (is_null($opens_at)) {
            array_push($this->openAPINullablesSetToNull, 'opens_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('opens_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($opens_at) && (!preg_match("/^([01]\\d|2[0-3]):[0-5]\\d$/", ObjectSerializer::toString($opens_at)))) {
            throw new \InvalidArgumentException("invalid value for \$opens_at when calling CalendarDay., must conform to the pattern /^([01]\\d|2[0-3]):[0-5]\\d$/.");
        }

        $this->container['opens_at'] = $opens_at;

        return $this;
    }

    /**
     * Gets closes_at
     *
     * @return string|null
     */
    public function getClosesAt()
    {
        return $this->container['closes_at'];
    }

    /**
     * Sets closes_at
     *
     * @param string|null $closes_at Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
     *
     * @return self
     */
    public function setClosesAt($closes_at)
    {
        if (is_null($closes_at)) {
            array_push($this->openAPINullablesSetToNull, 'closes_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('closes_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($closes_at) && (!preg_match("/^([01]\\d|2[0-3]):[0-5]\\d$/", ObjectSerializer::toString($closes_at)))) {
            throw new \InvalidArgumentException("invalid value for \$closes_at when calling CalendarDay., must conform to the pattern /^([01]\\d|2[0-3]):[0-5]\\d$/.");
        }

        $this->container['closes_at'] = $closes_at;

        return $this;
    }

    /**
     * Gets closure_reason
     *
     * @return \MtnManager\Model\ClosureReason|null
     */
    public function getClosureReason()
    {
        return $this->container['closure_reason'];
    }

    /**
     * Sets closure_reason
     *
     * @param \MtnManager\Model\ClosureReason|null $closure_reason closure_reason
     *
     * @return self
     */
    public function setClosureReason($closure_reason)
    {
        if (is_null($closure_reason)) {
            array_push($this->openAPINullablesSetToNull, 'closure_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('closure_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['closure_reason'] = $closure_reason;

        return $this;
    }

    /**
     * Gets special_event
     *
     * @return string|null
     */
    public function getSpecialEvent()
    {
        return $this->container['special_event'];
    }

    /**
     * Sets special_event
     *
     * @param string|null $special_event Special event for this day.
     *
     * @return self
     */
    public function setSpecialEvent($special_event)
    {
        if (is_null($special_event)) {
            array_push($this->openAPINullablesSetToNull, 'special_event');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('special_event', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['special_event'] = $special_event;

        return $this;
    }

    /**
     * Gets amenities
     *
     * @return \MtnManager\Model\AmenityCalendarEntry[]|null
     */
    public function getAmenities()
    {
        return $this->container['amenities'];
    }

    /**
     * Sets amenities
     *
     * @param \MtnManager\Model\AmenityCalendarEntry[]|null $amenities Per-amenity hours for this day. Only included when amenity hours are configured.
     *
     * @return self
     */
    public function setAmenities($amenities)
    {
        if (is_null($amenities)) {
            throw new \InvalidArgumentException('non-nullable amenities cannot be null');
        }
        $this->container['amenities'] = $amenities;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


