<?php
/**
 * DailyForecastImperial
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;

use \ArrayAccess;
use \MtnManager\ObjectSerializer;

/**
 * DailyForecastImperial Class Doc Comment
 *
 * @category Class
 * @description Daily forecast measurements in imperial units
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DailyForecastImperial implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DailyForecastImperial';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'temperature_high' => 'int',
        'temperature_low' => 'int',
        'snowfall_total' => 'int',
        'precipitation_total' => 'int',
        'wind_speed_max' => 'int',
        'wind_gust_max' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'temperature_high' => 'int32',
        'temperature_low' => 'int32',
        'snowfall_total' => 'int32',
        'precipitation_total' => 'int32',
        'wind_speed_max' => 'int32',
        'wind_gust_max' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'temperature_high' => false,
        'temperature_low' => false,
        'snowfall_total' => true,
        'precipitation_total' => true,
        'wind_speed_max' => true,
        'wind_gust_max' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'temperature_high' => 'temperature_high',
        'temperature_low' => 'temperature_low',
        'snowfall_total' => 'snowfall_total',
        'precipitation_total' => 'precipitation_total',
        'wind_speed_max' => 'wind_speed_max',
        'wind_gust_max' => 'wind_gust_max'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'temperature_high' => 'setTemperatureHigh',
        'temperature_low' => 'setTemperatureLow',
        'snowfall_total' => 'setSnowfallTotal',
        'precipitation_total' => 'setPrecipitationTotal',
        'wind_speed_max' => 'setWindSpeedMax',
        'wind_gust_max' => 'setWindGustMax'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'temperature_high' => 'getTemperatureHigh',
        'temperature_low' => 'getTemperatureLow',
        'snowfall_total' => 'getSnowfallTotal',
        'precipitation_total' => 'getPrecipitationTotal',
        'wind_speed_max' => 'getWindSpeedMax',
        'wind_gust_max' => 'getWindGustMax'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('temperature_high', $data ?? [], null);
        $this->setIfExists('temperature_low', $data ?? [], null);
        $this->setIfExists('snowfall_total', $data ?? [], null);
        $this->setIfExists('precipitation_total', $data ?? [], null);
        $this->setIfExists('wind_speed_max', $data ?? [], null);
        $this->setIfExists('wind_gust_max', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['temperature_high'] === null) {
            $invalidProperties[] = "'temperature_high' can't be null";
        }
        if ($this->container['temperature_low'] === null) {
            $invalidProperties[] = "'temperature_low' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets temperature_high
     *
     * @return int
     */
    public function getTemperatureHigh()
    {
        return $this->container['temperature_high'];
    }

    /**
     * Sets temperature_high
     *
     * @param int $temperature_high High temperature in Fahrenheit
     *
     * @return self
     */
    public function setTemperatureHigh($temperature_high)
    {
        if (is_null($temperature_high)) {
            throw new \InvalidArgumentException('non-nullable temperature_high cannot be null');
        }
        $this->container['temperature_high'] = $temperature_high;

        return $this;
    }

    /**
     * Gets temperature_low
     *
     * @return int
     */
    public function getTemperatureLow()
    {
        return $this->container['temperature_low'];
    }

    /**
     * Sets temperature_low
     *
     * @param int $temperature_low Low temperature in Fahrenheit
     *
     * @return self
     */
    public function setTemperatureLow($temperature_low)
    {
        if (is_null($temperature_low)) {
            throw new \InvalidArgumentException('non-nullable temperature_low cannot be null');
        }
        $this->container['temperature_low'] = $temperature_low;

        return $this;
    }

    /**
     * Gets snowfall_total
     *
     * @return int|null
     */
    public function getSnowfallTotal()
    {
        return $this->container['snowfall_total'];
    }

    /**
     * Sets snowfall_total
     *
     * @param int|null $snowfall_total Total snowfall expected in inches
     *
     * @return self
     */
    public function setSnowfallTotal($snowfall_total)
    {
        if (is_null($snowfall_total)) {
            array_push($this->openAPINullablesSetToNull, 'snowfall_total');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('snowfall_total', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['snowfall_total'] = $snowfall_total;

        return $this;
    }

    /**
     * Gets precipitation_total
     *
     * @return int|null
     */
    public function getPrecipitationTotal()
    {
        return $this->container['precipitation_total'];
    }

    /**
     * Sets precipitation_total
     *
     * @param int|null $precipitation_total Total precipitation expected in inches
     *
     * @return self
     */
    public function setPrecipitationTotal($precipitation_total)
    {
        if (is_null($precipitation_total)) {
            array_push($this->openAPINullablesSetToNull, 'precipitation_total');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('precipitation_total', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['precipitation_total'] = $precipitation_total;

        return $this;
    }

    /**
     * Gets wind_speed_max
     *
     * @return int|null
     */
    public function getWindSpeedMax()
    {
        return $this->container['wind_speed_max'];
    }

    /**
     * Sets wind_speed_max
     *
     * @param int|null $wind_speed_max Maximum wind speed in mph
     *
     * @return self
     */
    public function setWindSpeedMax($wind_speed_max)
    {
        if (is_null($wind_speed_max)) {
            array_push($this->openAPINullablesSetToNull, 'wind_speed_max');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wind_speed_max', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['wind_speed_max'] = $wind_speed_max;

        return $this;
    }

    /**
     * Gets wind_gust_max
     *
     * @return int|null
     */
    public function getWindGustMax()
    {
        return $this->container['wind_gust_max'];
    }

    /**
     * Sets wind_gust_max
     *
     * @param int|null $wind_gust_max Maximum wind gust in mph
     *
     * @return self
     */
    public function setWindGustMax($wind_gust_max)
    {
        if (is_null($wind_gust_max)) {
            array_push($this->openAPINullablesSetToNull, 'wind_gust_max');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wind_gust_max', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['wind_gust_max'] = $wind_gust_max;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


