<?php
/**
 * FullReport
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;

use \ArrayAccess;
use \MtnManager\ObjectSerializer;

/**
 * FullReport Class Doc Comment
 *
 * @category Class
 * @description The all-in-one endpoint containing the full report — resort information, current status,  runs, lifts, snow, terrain parks, summer trails, hours, and weather.
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FullReport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FullReport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'resort' => '\MtnManager\Model\ResortInfo',
        'status' => '\MtnManager\Model\Overview',
        'snow' => '\MtnManager\Model\SnowReport[]',
        'lifts' => '\MtnManager\Model\Lift[]',
        'runs' => '\MtnManager\Model\Run[]',
        'terrain_parks' => '\MtnManager\Model\TerrainPark[]',
        'summer_trails' => '\MtnManager\Model\SummerTrail[]',
        'hours' => '\MtnManager\Model\OperatingHours',
        'weather' => '\MtnManager\Model\Weather'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'resort' => null,
        'status' => null,
        'snow' => null,
        'lifts' => null,
        'runs' => null,
        'terrain_parks' => null,
        'summer_trails' => null,
        'hours' => null,
        'weather' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'resort' => false,
        'status' => false,
        'snow' => false,
        'lifts' => false,
        'runs' => false,
        'terrain_parks' => false,
        'summer_trails' => false,
        'hours' => false,
        'weather' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'resort' => 'resort',
        'status' => 'status',
        'snow' => 'snow',
        'lifts' => 'lifts',
        'runs' => 'runs',
        'terrain_parks' => 'terrain_parks',
        'summer_trails' => 'summer_trails',
        'hours' => 'hours',
        'weather' => 'weather'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'resort' => 'setResort',
        'status' => 'setStatus',
        'snow' => 'setSnow',
        'lifts' => 'setLifts',
        'runs' => 'setRuns',
        'terrain_parks' => 'setTerrainParks',
        'summer_trails' => 'setSummerTrails',
        'hours' => 'setHours',
        'weather' => 'setWeather'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'resort' => 'getResort',
        'status' => 'getStatus',
        'snow' => 'getSnow',
        'lifts' => 'getLifts',
        'runs' => 'getRuns',
        'terrain_parks' => 'getTerrainParks',
        'summer_trails' => 'getSummerTrails',
        'hours' => 'getHours',
        'weather' => 'getWeather'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('resort', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('snow', $data ?? [], null);
        $this->setIfExists('lifts', $data ?? [], null);
        $this->setIfExists('runs', $data ?? [], null);
        $this->setIfExists('terrain_parks', $data ?? [], null);
        $this->setIfExists('summer_trails', $data ?? [], null);
        $this->setIfExists('hours', $data ?? [], null);
        $this->setIfExists('weather', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['resort'] === null) {
            $invalidProperties[] = "'resort' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['snow'] === null) {
            $invalidProperties[] = "'snow' can't be null";
        }
        if ($this->container['lifts'] === null) {
            $invalidProperties[] = "'lifts' can't be null";
        }
        if ($this->container['runs'] === null) {
            $invalidProperties[] = "'runs' can't be null";
        }
        if ($this->container['terrain_parks'] === null) {
            $invalidProperties[] = "'terrain_parks' can't be null";
        }
        if ($this->container['summer_trails'] === null) {
            $invalidProperties[] = "'summer_trails' can't be null";
        }
        if ($this->container['hours'] === null) {
            $invalidProperties[] = "'hours' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets resort
     *
     * @return \MtnManager\Model\ResortInfo
     */
    public function getResort()
    {
        return $this->container['resort'];
    }

    /**
     * Sets resort
     *
     * @param \MtnManager\Model\ResortInfo $resort resort
     *
     * @return self
     */
    public function setResort($resort)
    {
        if (is_null($resort)) {
            throw new \InvalidArgumentException('non-nullable resort cannot be null');
        }
        $this->container['resort'] = $resort;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \MtnManager\Model\Overview
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \MtnManager\Model\Overview $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets snow
     *
     * @return \MtnManager\Model\SnowReport[]
     */
    public function getSnow()
    {
        return $this->container['snow'];
    }

    /**
     * Sets snow
     *
     * @param \MtnManager\Model\SnowReport[] $snow Provides current snow conditions including base depth, surface conditions,  and snowfall totals in both metric and imperial units.   May contain multiple, representing different reporting areas.
     *
     * @return self
     */
    public function setSnow($snow)
    {
        if (is_null($snow)) {
            throw new \InvalidArgumentException('non-nullable snow cannot be null');
        }
        $this->container['snow'] = $snow;

        return $this;
    }

    /**
     * Gets lifts
     *
     * @return \MtnManager\Model\Lift[]
     */
    public function getLifts()
    {
        return $this->container['lifts'];
    }

    /**
     * Sets lifts
     *
     * @param \MtnManager\Model\Lift[] $lifts List of all lifts at the resort with their current operational status,  type, and optional wait time information.
     *
     * @return self
     */
    public function setLifts($lifts)
    {
        if (is_null($lifts)) {
            throw new \InvalidArgumentException('non-nullable lifts cannot be null');
        }
        $this->container['lifts'] = $lifts;

        return $this;
    }

    /**
     * Gets runs
     *
     * @return \MtnManager\Model\Run[]
     */
    public function getRuns()
    {
        return $this->container['runs'];
    }

    /**
     * Sets runs
     *
     * @param \MtnManager\Model\Run[] $runs List of all runs at the resort with their current status,  grooming information, and difficulty rating.
     *
     * @return self
     */
    public function setRuns($runs)
    {
        if (is_null($runs)) {
            throw new \InvalidArgumentException('non-nullable runs cannot be null');
        }
        $this->container['runs'] = $runs;

        return $this;
    }

    /**
     * Gets terrain_parks
     *
     * @return \MtnManager\Model\TerrainPark[]
     */
    public function getTerrainParks()
    {
        return $this->container['terrain_parks'];
    }

    /**
     * Sets terrain_parks
     *
     * @param \MtnManager\Model\TerrainPark[] $terrain_parks List of all terrain parks at the resort with their current status,  condition notes, and list of features (jumps, boxes, rails, etc.) within them.
     *
     * @return self
     */
    public function setTerrainParks($terrain_parks)
    {
        if (is_null($terrain_parks)) {
            throw new \InvalidArgumentException('non-nullable terrain_parks cannot be null');
        }
        $this->container['terrain_parks'] = $terrain_parks;

        return $this;
    }

    /**
     * Gets summer_trails
     *
     * @return \MtnManager\Model\SummerTrail[]
     */
    public function getSummerTrails()
    {
        return $this->container['summer_trails'];
    }

    /**
     * Sets summer_trails
     *
     * @param \MtnManager\Model\SummerTrail[] $summer_trails List of all summer trails at the resort with their current status,  type (e.g. hiking, mountain biking), and optional difficulty rating.
     *
     * @return self
     */
    public function setSummerTrails($summer_trails)
    {
        if (is_null($summer_trails)) {
            throw new \InvalidArgumentException('non-nullable summer_trails cannot be null');
        }
        $this->container['summer_trails'] = $summer_trails;

        return $this;
    }

    /**
     * Gets hours
     *
     * @return \MtnManager\Model\OperatingHours
     */
    public function getHours()
    {
        return $this->container['hours'];
    }

    /**
     * Sets hours
     *
     * @param \MtnManager\Model\OperatingHours $hours hours
     *
     * @return self
     */
    public function setHours($hours)
    {
        if (is_null($hours)) {
            throw new \InvalidArgumentException('non-nullable hours cannot be null');
        }
        $this->container['hours'] = $hours;

        return $this;
    }

    /**
     * Gets weather
     *
     * @return \MtnManager\Model\Weather|null
     */
    public function getWeather()
    {
        return $this->container['weather'];
    }

    /**
     * Sets weather
     *
     * @param \MtnManager\Model\Weather|null $weather weather
     *
     * @return self
     */
    public function setWeather($weather)
    {
        if (is_null($weather)) {
            array_push($this->openAPINullablesSetToNull, 'weather');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('weather', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['weather'] = $weather;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


