<?php
/**
 * LiftType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;
use \MtnManager\ObjectSerializer;

/**
 * LiftType Class Doc Comment
 *
 * @category Class
 * @description Type of ski lift
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LiftType
{
    /**
     * Possible values of this enum
     */
    public const GONDOLA = 'gondola';

    public const TRAM = 'tram';

    public const EIGHT_PACK = 'eight_pack';

    public const SIX_PACK = 'six_pack';

    public const QUAD = 'quad';

    public const TRIPLE = 'triple';

    public const DOUBLE = 'double';

    public const MAGIC_CARPET = 'magic_carpet';

    public const T_BAR = 't_bar';

    public const PLATTER = 'platter';

    public const ROPE_TOW = 'rope_tow';

    public const FUNICULAR = 'funicular';

    public const OTHER = 'other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GONDOLA,
            self::TRAM,
            self::EIGHT_PACK,
            self::SIX_PACK,
            self::QUAD,
            self::TRIPLE,
            self::DOUBLE,
            self::MAGIC_CARPET,
            self::T_BAR,
            self::PLATTER,
            self::ROPE_TOW,
            self::FUNICULAR,
            self::OTHER
        ];
    }
}


