<?php
/**
 * ParkingLotStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;
use \MtnManager\ObjectSerializer;

/**
 * ParkingLotStatus Class Doc Comment
 *
 * @category Class
 * @description Operational status of a parking lot.
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ParkingLotStatus
{
    /**
     * Possible values of this enum
     */
    public const OPEN = 'open';

    public const CLOSED = 'closed';

    public const FULL = 'full';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OPEN,
            self::CLOSED,
            self::FULL
        ];
    }
}


