<?php
/**
 * Run
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;

use \ArrayAccess;
use \MtnManager\ObjectSerializer;

/**
 * Run Class Doc Comment
 *
 * @category Class
 * @description Represents a single run at the resort with its current status,  grooming information, and difficulty rating.
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Run implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Run';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uuid' => 'string',
        'name' => 'string',
        'slug' => 'string',
        'number' => 'int',
        'difficulty' => '\MtnManager\Model\RunDifficulty',
        'status' => '\MtnManager\Model\RunStatus',
        'last_groomed' => '\DateTime',
        'groomed_today' => 'bool',
        'snowmaking' => 'bool',
        'night_skiing' => 'bool',
        'condition_notes' => 'string',
        'area_uuid' => 'string',
        'area_name' => 'string',
        'area_display_order' => 'int',
        'updated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uuid' => null,
        'name' => null,
        'slug' => null,
        'number' => 'int32',
        'difficulty' => null,
        'status' => null,
        'last_groomed' => 'date-time',
        'groomed_today' => null,
        'snowmaking' => null,
        'night_skiing' => null,
        'condition_notes' => null,
        'area_uuid' => null,
        'area_name' => null,
        'area_display_order' => 'int32',
        'updated_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uuid' => false,
        'name' => false,
        'slug' => false,
        'number' => true,
        'difficulty' => false,
        'status' => false,
        'last_groomed' => true,
        'groomed_today' => false,
        'snowmaking' => false,
        'night_skiing' => false,
        'condition_notes' => false,
        'area_uuid' => true,
        'area_name' => true,
        'area_display_order' => true,
        'updated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'name' => 'name',
        'slug' => 'slug',
        'number' => 'number',
        'difficulty' => 'difficulty',
        'status' => 'status',
        'last_groomed' => 'last_groomed',
        'groomed_today' => 'groomed_today',
        'snowmaking' => 'snowmaking',
        'night_skiing' => 'night_skiing',
        'condition_notes' => 'condition_notes',
        'area_uuid' => 'area_uuid',
        'area_name' => 'area_name',
        'area_display_order' => 'area_display_order',
        'updated_at' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'name' => 'setName',
        'slug' => 'setSlug',
        'number' => 'setNumber',
        'difficulty' => 'setDifficulty',
        'status' => 'setStatus',
        'last_groomed' => 'setLastGroomed',
        'groomed_today' => 'setGroomedToday',
        'snowmaking' => 'setSnowmaking',
        'night_skiing' => 'setNightSkiing',
        'condition_notes' => 'setConditionNotes',
        'area_uuid' => 'setAreaUuid',
        'area_name' => 'setAreaName',
        'area_display_order' => 'setAreaDisplayOrder',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'name' => 'getName',
        'slug' => 'getSlug',
        'number' => 'getNumber',
        'difficulty' => 'getDifficulty',
        'status' => 'getStatus',
        'last_groomed' => 'getLastGroomed',
        'groomed_today' => 'getGroomedToday',
        'snowmaking' => 'getSnowmaking',
        'night_skiing' => 'getNightSkiing',
        'condition_notes' => 'getConditionNotes',
        'area_uuid' => 'getAreaUuid',
        'area_name' => 'getAreaName',
        'area_display_order' => 'getAreaDisplayOrder',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('difficulty', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('last_groomed', $data ?? [], null);
        $this->setIfExists('groomed_today', $data ?? [], null);
        $this->setIfExists('snowmaking', $data ?? [], null);
        $this->setIfExists('night_skiing', $data ?? [], null);
        $this->setIfExists('condition_notes', $data ?? [], null);
        $this->setIfExists('area_uuid', $data ?? [], null);
        $this->setIfExists('area_name', $data ?? [], null);
        $this->setIfExists('area_display_order', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid'] === null) {
            $invalidProperties[] = "'uuid' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        if ($this->container['difficulty'] === null) {
            $invalidProperties[] = "'difficulty' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['groomed_today'] === null) {
            $invalidProperties[] = "'groomed_today' can't be null";
        }
        if ($this->container['snowmaking'] === null) {
            $invalidProperties[] = "'snowmaking' can't be null";
        }
        if ($this->container['night_skiing'] === null) {
            $invalidProperties[] = "'night_skiing' can't be null";
        }
        if ($this->container['condition_notes'] === null) {
            $invalidProperties[] = "'condition_notes' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string $uuid Unique identifier for the run.
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Display name of the run.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug URL-friendly name of the run.
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets number
     *
     * @return int|null
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param int|null $number Optional run number.
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            array_push($this->openAPINullablesSetToNull, 'number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets difficulty
     *
     * @return \MtnManager\Model\RunDifficulty
     */
    public function getDifficulty()
    {
        return $this->container['difficulty'];
    }

    /**
     * Sets difficulty
     *
     * @param \MtnManager\Model\RunDifficulty $difficulty Difficulty rating of the run.
     *
     * @return self
     */
    public function setDifficulty($difficulty)
    {
        if (is_null($difficulty)) {
            throw new \InvalidArgumentException('non-nullable difficulty cannot be null');
        }
        $this->container['difficulty'] = $difficulty;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \MtnManager\Model\RunStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \MtnManager\Model\RunStatus $status Current operational status (open, closed, or unknown).
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets last_groomed
     *
     * @return \DateTime|null
     */
    public function getLastGroomed()
    {
        return $this->container['last_groomed'];
    }

    /**
     * Sets last_groomed
     *
     * @param \DateTime|null $last_groomed When the run was last groomed.  `null` if never groomed, or if the runs grooming feature is disabled.
     *
     * @return self
     */
    public function setLastGroomed($last_groomed)
    {
        if (is_null($last_groomed)) {
            array_push($this->openAPINullablesSetToNull, 'last_groomed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_groomed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_groomed'] = $last_groomed;

        return $this;
    }

    /**
     * Gets groomed_today
     *
     * @return bool
     */
    public function getGroomedToday()
    {
        return $this->container['groomed_today'];
    }

    /**
     * Sets groomed_today
     *
     * @param bool $groomed_today Whether the run was groomed within the last 24 hours.
     *
     * @return self
     */
    public function setGroomedToday($groomed_today)
    {
        if (is_null($groomed_today)) {
            throw new \InvalidArgumentException('non-nullable groomed_today cannot be null');
        }
        $this->container['groomed_today'] = $groomed_today;

        return $this;
    }

    /**
     * Gets snowmaking
     *
     * @return bool
     */
    public function getSnowmaking()
    {
        return $this->container['snowmaking'];
    }

    /**
     * Sets snowmaking
     *
     * @param bool $snowmaking Whether the run has snowmaking capabilities.
     *
     * @return self
     */
    public function setSnowmaking($snowmaking)
    {
        if (is_null($snowmaking)) {
            throw new \InvalidArgumentException('non-nullable snowmaking cannot be null');
        }
        $this->container['snowmaking'] = $snowmaking;

        return $this;
    }

    /**
     * Gets night_skiing
     *
     * @return bool
     */
    public function getNightSkiing()
    {
        return $this->container['night_skiing'];
    }

    /**
     * Sets night_skiing
     *
     * @param bool $night_skiing Whether the run is available for night skiing.
     *
     * @return self
     */
    public function setNightSkiing($night_skiing)
    {
        if (is_null($night_skiing)) {
            throw new \InvalidArgumentException('non-nullable night_skiing cannot be null');
        }
        $this->container['night_skiing'] = $night_skiing;

        return $this;
    }

    /**
     * Gets condition_notes
     *
     * @return string
     */
    public function getConditionNotes()
    {
        return $this->container['condition_notes'];
    }

    /**
     * Sets condition_notes
     *
     * @param string $condition_notes Notes about current conditions on this run.
     *
     * @return self
     */
    public function setConditionNotes($condition_notes)
    {
        if (is_null($condition_notes)) {
            throw new \InvalidArgumentException('non-nullable condition_notes cannot be null');
        }
        $this->container['condition_notes'] = $condition_notes;

        return $this;
    }

    /**
     * Gets area_uuid
     *
     * @return string|null
     */
    public function getAreaUuid()
    {
        return $this->container['area_uuid'];
    }

    /**
     * Sets area_uuid
     *
     * @param string|null $area_uuid UUID of the area this run belongs to, if assigned.
     *
     * @return self
     */
    public function setAreaUuid($area_uuid)
    {
        if (is_null($area_uuid)) {
            array_push($this->openAPINullablesSetToNull, 'area_uuid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_uuid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_uuid'] = $area_uuid;

        return $this;
    }

    /**
     * Gets area_name
     *
     * @return string|null
     */
    public function getAreaName()
    {
        return $this->container['area_name'];
    }

    /**
     * Sets area_name
     *
     * @param string|null $area_name Name of the area this run belongs to, if assigned.
     *
     * @return self
     */
    public function setAreaName($area_name)
    {
        if (is_null($area_name)) {
            array_push($this->openAPINullablesSetToNull, 'area_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_name'] = $area_name;

        return $this;
    }

    /**
     * Gets area_display_order
     *
     * @return int|null
     */
    public function getAreaDisplayOrder()
    {
        return $this->container['area_display_order'];
    }

    /**
     * Sets area_display_order
     *
     * @param int|null $area_display_order Display order of the area this run belongs to, if assigned, for sorting purposes.
     *
     * @return self
     */
    public function setAreaDisplayOrder($area_display_order)
    {
        if (is_null($area_display_order)) {
            array_push($this->openAPINullablesSetToNull, 'area_display_order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_display_order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_display_order'] = $area_display_order;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at When this run's information was last updated.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


