<?php
/**
 * SeasonType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;
use \MtnManager\ObjectSerializer;

/**
 * SeasonType Class Doc Comment
 *
 * @category Class
 * @description A resort&#39;s season: winter or summer as its weekly operating hours say  (&#x60;OperatingHoursDb::season_type&#x60;), or closed outside every season (see  &#x60;utils::hours::season_on&#x60;).
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SeasonType
{
    /**
     * Possible values of this enum
     */
    public const WINTER = 'winter';

    public const SUMMER = 'summer';

    public const CLOSED = 'closed';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WINTER,
            self::SUMMER,
            self::CLOSED,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


