<?php
/**
 * SnowMetrics
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;

use \ArrayAccess;
use \MtnManager\ObjectSerializer;

/**
 * SnowMetrics Class Doc Comment
 *
 * @category Class
 * @description Contains snowfall totals for various time periods. Values are provided  in the unit indicated by the parent field name (cm or inches).
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SnowMetrics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SnowMetrics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'overnight' => 'int',
        'last_24h' => 'int',
        'last_48h' => 'int',
        'last_7days' => 'int',
        'season_total' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'overnight' => 'int32',
        'last_24h' => 'int32',
        'last_48h' => 'int32',
        'last_7days' => 'int32',
        'season_total' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'overnight' => false,
        'last_24h' => false,
        'last_48h' => false,
        'last_7days' => false,
        'season_total' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'overnight' => 'overnight',
        'last_24h' => 'last_24h',
        'last_48h' => 'last_48h',
        'last_7days' => 'last_7days',
        'season_total' => 'season_total'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'overnight' => 'setOvernight',
        'last_24h' => 'setLast24h',
        'last_48h' => 'setLast48h',
        'last_7days' => 'setLast7days',
        'season_total' => 'setSeasonTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'overnight' => 'getOvernight',
        'last_24h' => 'getLast24h',
        'last_48h' => 'getLast48h',
        'last_7days' => 'getLast7days',
        'season_total' => 'getSeasonTotal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('overnight', $data ?? [], null);
        $this->setIfExists('last_24h', $data ?? [], null);
        $this->setIfExists('last_48h', $data ?? [], null);
        $this->setIfExists('last_7days', $data ?? [], null);
        $this->setIfExists('season_total', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['overnight'] === null) {
            $invalidProperties[] = "'overnight' can't be null";
        }
        if ($this->container['last_24h'] === null) {
            $invalidProperties[] = "'last_24h' can't be null";
        }
        if ($this->container['last_48h'] === null) {
            $invalidProperties[] = "'last_48h' can't be null";
        }
        if ($this->container['last_7days'] === null) {
            $invalidProperties[] = "'last_7days' can't be null";
        }
        if ($this->container['season_total'] === null) {
            $invalidProperties[] = "'season_total' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets overnight
     *
     * @return int
     */
    public function getOvernight()
    {
        return $this->container['overnight'];
    }

    /**
     * Sets overnight
     *
     * @param int $overnight Snowfall during the overnight window (midnight to 9 AM local timezone).
     *
     * @return self
     */
    public function setOvernight($overnight)
    {
        if (is_null($overnight)) {
            throw new \InvalidArgumentException('non-nullable overnight cannot be null');
        }
        $this->container['overnight'] = $overnight;

        return $this;
    }

    /**
     * Gets last_24h
     *
     * @return int
     */
    public function getLast24h()
    {
        return $this->container['last_24h'];
    }

    /**
     * Sets last_24h
     *
     * @param int $last_24h Snowfall in the last 24 hours.
     *
     * @return self
     */
    public function setLast24h($last_24h)
    {
        if (is_null($last_24h)) {
            throw new \InvalidArgumentException('non-nullable last_24h cannot be null');
        }
        $this->container['last_24h'] = $last_24h;

        return $this;
    }

    /**
     * Gets last_48h
     *
     * @return int
     */
    public function getLast48h()
    {
        return $this->container['last_48h'];
    }

    /**
     * Sets last_48h
     *
     * @param int $last_48h Snowfall in the last 48 hours.
     *
     * @return self
     */
    public function setLast48h($last_48h)
    {
        if (is_null($last_48h)) {
            throw new \InvalidArgumentException('non-nullable last_48h cannot be null');
        }
        $this->container['last_48h'] = $last_48h;

        return $this;
    }

    /**
     * Gets last_7days
     *
     * @return int
     */
    public function getLast7days()
    {
        return $this->container['last_7days'];
    }

    /**
     * Sets last_7days
     *
     * @param int $last_7days Snowfall in the last 7 days.
     *
     * @return self
     */
    public function setLast7days($last_7days)
    {
        if (is_null($last_7days)) {
            throw new \InvalidArgumentException('non-nullable last_7days cannot be null');
        }
        $this->container['last_7days'] = $last_7days;

        return $this;
    }

    /**
     * Gets season_total
     *
     * @return int
     */
    public function getSeasonTotal()
    {
        return $this->container['season_total'];
    }

    /**
     * Sets season_total
     *
     * @param int $season_total Total snowfall for the current season.
     *
     * @return self
     */
    public function setSeasonTotal($season_total)
    {
        if (is_null($season_total)) {
            throw new \InvalidArgumentException('non-nullable season_total cannot be null');
        }
        $this->container['season_total'] = $season_total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


