<?php
/**
 * SnowReport
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;

use \ArrayAccess;
use \MtnManager\ObjectSerializer;

/**
 * SnowReport Class Doc Comment
 *
 * @category Class
 * @description Provides current snow conditions for a specific area or the entire resort,  including base depth, surface conditions, and snowfall totals in both  metric and imperial units.
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SnowReport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SnowReport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uuid' => 'string',
        'area_uuid' => 'string',
        'area_name' => 'string',
        'area_display_order' => 'int',
        'base_depth_cm' => 'int',
        'base_depth_in' => 'int',
        'surface_condition' => '\MtnManager\Model\SurfaceCondition',
        'secondary_surface_condition' => '\MtnManager\Model\SurfaceCondition',
        'condition_notes' => 'string',
        'snowfall_cm' => '\MtnManager\Model\SnowMetrics',
        'snowfall_in' => '\MtnManager\Model\SnowMetrics',
        'reported_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uuid' => null,
        'area_uuid' => null,
        'area_name' => null,
        'area_display_order' => 'int32',
        'base_depth_cm' => 'int32',
        'base_depth_in' => 'int32',
        'surface_condition' => null,
        'secondary_surface_condition' => null,
        'condition_notes' => null,
        'snowfall_cm' => null,
        'snowfall_in' => null,
        'reported_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uuid' => false,
        'area_uuid' => true,
        'area_name' => true,
        'area_display_order' => true,
        'base_depth_cm' => true,
        'base_depth_in' => true,
        'surface_condition' => true,
        'secondary_surface_condition' => true,
        'condition_notes' => false,
        'snowfall_cm' => false,
        'snowfall_in' => false,
        'reported_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'area_uuid' => 'area_uuid',
        'area_name' => 'area_name',
        'area_display_order' => 'area_display_order',
        'base_depth_cm' => 'base_depth_cm',
        'base_depth_in' => 'base_depth_in',
        'surface_condition' => 'surface_condition',
        'secondary_surface_condition' => 'secondary_surface_condition',
        'condition_notes' => 'condition_notes',
        'snowfall_cm' => 'snowfall_cm',
        'snowfall_in' => 'snowfall_in',
        'reported_at' => 'reported_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'area_uuid' => 'setAreaUuid',
        'area_name' => 'setAreaName',
        'area_display_order' => 'setAreaDisplayOrder',
        'base_depth_cm' => 'setBaseDepthCm',
        'base_depth_in' => 'setBaseDepthIn',
        'surface_condition' => 'setSurfaceCondition',
        'secondary_surface_condition' => 'setSecondarySurfaceCondition',
        'condition_notes' => 'setConditionNotes',
        'snowfall_cm' => 'setSnowfallCm',
        'snowfall_in' => 'setSnowfallIn',
        'reported_at' => 'setReportedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'area_uuid' => 'getAreaUuid',
        'area_name' => 'getAreaName',
        'area_display_order' => 'getAreaDisplayOrder',
        'base_depth_cm' => 'getBaseDepthCm',
        'base_depth_in' => 'getBaseDepthIn',
        'surface_condition' => 'getSurfaceCondition',
        'secondary_surface_condition' => 'getSecondarySurfaceCondition',
        'condition_notes' => 'getConditionNotes',
        'snowfall_cm' => 'getSnowfallCm',
        'snowfall_in' => 'getSnowfallIn',
        'reported_at' => 'getReportedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('area_uuid', $data ?? [], null);
        $this->setIfExists('area_name', $data ?? [], null);
        $this->setIfExists('area_display_order', $data ?? [], null);
        $this->setIfExists('base_depth_cm', $data ?? [], null);
        $this->setIfExists('base_depth_in', $data ?? [], null);
        $this->setIfExists('surface_condition', $data ?? [], null);
        $this->setIfExists('secondary_surface_condition', $data ?? [], null);
        $this->setIfExists('condition_notes', $data ?? [], null);
        $this->setIfExists('snowfall_cm', $data ?? [], null);
        $this->setIfExists('snowfall_in', $data ?? [], null);
        $this->setIfExists('reported_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid'] === null) {
            $invalidProperties[] = "'uuid' can't be null";
        }
        if ($this->container['condition_notes'] === null) {
            $invalidProperties[] = "'condition_notes' can't be null";
        }
        if ($this->container['snowfall_cm'] === null) {
            $invalidProperties[] = "'snowfall_cm' can't be null";
        }
        if ($this->container['snowfall_in'] === null) {
            $invalidProperties[] = "'snowfall_in' can't be null";
        }
        if ($this->container['reported_at'] === null) {
            $invalidProperties[] = "'reported_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string $uuid Unique identifier for this snow report.
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets area_uuid
     *
     * @return string|null
     */
    public function getAreaUuid()
    {
        return $this->container['area_uuid'];
    }

    /**
     * Sets area_uuid
     *
     * @param string|null $area_uuid UUID of the area this report covers, if area-specific.  `null` for resort-wide reports.
     *
     * @return self
     */
    public function setAreaUuid($area_uuid)
    {
        if (is_null($area_uuid)) {
            array_push($this->openAPINullablesSetToNull, 'area_uuid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_uuid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_uuid'] = $area_uuid;

        return $this;
    }

    /**
     * Gets area_name
     *
     * @return string|null
     */
    public function getAreaName()
    {
        return $this->container['area_name'];
    }

    /**
     * Sets area_name
     *
     * @param string|null $area_name Name of the area this report covers, if area-specific.
     *
     * @return self
     */
    public function setAreaName($area_name)
    {
        if (is_null($area_name)) {
            array_push($this->openAPINullablesSetToNull, 'area_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_name'] = $area_name;

        return $this;
    }

    /**
     * Gets area_display_order
     *
     * @return int|null
     */
    public function getAreaDisplayOrder()
    {
        return $this->container['area_display_order'];
    }

    /**
     * Sets area_display_order
     *
     * @param int|null $area_display_order Display order of the area this report covers, if area-specific, for sorting purposes.
     *
     * @return self
     */
    public function setAreaDisplayOrder($area_display_order)
    {
        if (is_null($area_display_order)) {
            array_push($this->openAPINullablesSetToNull, 'area_display_order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_display_order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_display_order'] = $area_display_order;

        return $this;
    }

    /**
     * Gets base_depth_cm
     *
     * @return int|null
     */
    public function getBaseDepthCm()
    {
        return $this->container['base_depth_cm'];
    }

    /**
     * Sets base_depth_cm
     *
     * @param int|null $base_depth_cm Current base depth in centimeters.  Not included if the base depth feature is disabled.
     *
     * @return self
     */
    public function setBaseDepthCm($base_depth_cm)
    {
        if (is_null($base_depth_cm)) {
            array_push($this->openAPINullablesSetToNull, 'base_depth_cm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('base_depth_cm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['base_depth_cm'] = $base_depth_cm;

        return $this;
    }

    /**
     * Gets base_depth_in
     *
     * @return int|null
     */
    public function getBaseDepthIn()
    {
        return $this->container['base_depth_in'];
    }

    /**
     * Sets base_depth_in
     *
     * @param int|null $base_depth_in Current base depth in inches.  Not included if the base depth feature is disabled.
     *
     * @return self
     */
    public function setBaseDepthIn($base_depth_in)
    {
        if (is_null($base_depth_in)) {
            array_push($this->openAPINullablesSetToNull, 'base_depth_in');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('base_depth_in', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['base_depth_in'] = $base_depth_in;

        return $this;
    }

    /**
     * Gets surface_condition
     *
     * @return \MtnManager\Model\SurfaceCondition|null
     */
    public function getSurfaceCondition()
    {
        return $this->container['surface_condition'];
    }

    /**
     * Sets surface_condition
     *
     * @param \MtnManager\Model\SurfaceCondition|null $surface_condition surface_condition
     *
     * @return self
     */
    public function setSurfaceCondition($surface_condition)
    {
        if (is_null($surface_condition)) {
            array_push($this->openAPINullablesSetToNull, 'surface_condition');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('surface_condition', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['surface_condition'] = $surface_condition;

        return $this;
    }

    /**
     * Gets secondary_surface_condition
     *
     * @return \MtnManager\Model\SurfaceCondition|null
     */
    public function getSecondarySurfaceCondition()
    {
        return $this->container['secondary_surface_condition'];
    }

    /**
     * Sets secondary_surface_condition
     *
     * @param \MtnManager\Model\SurfaceCondition|null $secondary_surface_condition secondary_surface_condition
     *
     * @return self
     */
    public function setSecondarySurfaceCondition($secondary_surface_condition)
    {
        if (is_null($secondary_surface_condition)) {
            array_push($this->openAPINullablesSetToNull, 'secondary_surface_condition');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('secondary_surface_condition', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['secondary_surface_condition'] = $secondary_surface_condition;

        return $this;
    }

    /**
     * Gets condition_notes
     *
     * @return string
     */
    public function getConditionNotes()
    {
        return $this->container['condition_notes'];
    }

    /**
     * Sets condition_notes
     *
     * @param string $condition_notes Additional notes about current snow conditions, e.g. groomer's notes
     *
     * @return self
     */
    public function setConditionNotes($condition_notes)
    {
        if (is_null($condition_notes)) {
            throw new \InvalidArgumentException('non-nullable condition_notes cannot be null');
        }
        $this->container['condition_notes'] = $condition_notes;

        return $this;
    }

    /**
     * Gets snowfall_cm
     *
     * @return \MtnManager\Model\SnowMetrics
     */
    public function getSnowfallCm()
    {
        return $this->container['snowfall_cm'];
    }

    /**
     * Sets snowfall_cm
     *
     * @param \MtnManager\Model\SnowMetrics $snowfall_cm Snowfall accumulation metrics in centimeters.
     *
     * @return self
     */
    public function setSnowfallCm($snowfall_cm)
    {
        if (is_null($snowfall_cm)) {
            throw new \InvalidArgumentException('non-nullable snowfall_cm cannot be null');
        }
        $this->container['snowfall_cm'] = $snowfall_cm;

        return $this;
    }

    /**
     * Gets snowfall_in
     *
     * @return \MtnManager\Model\SnowMetrics
     */
    public function getSnowfallIn()
    {
        return $this->container['snowfall_in'];
    }

    /**
     * Sets snowfall_in
     *
     * @param \MtnManager\Model\SnowMetrics $snowfall_in Snowfall accumulation metrics in inches.
     *
     * @return self
     */
    public function setSnowfallIn($snowfall_in)
    {
        if (is_null($snowfall_in)) {
            throw new \InvalidArgumentException('non-nullable snowfall_in cannot be null');
        }
        $this->container['snowfall_in'] = $snowfall_in;

        return $this;
    }

    /**
     * Gets reported_at
     *
     * @return \DateTime
     */
    public function getReportedAt()
    {
        return $this->container['reported_at'];
    }

    /**
     * Sets reported_at
     *
     * @param \DateTime $reported_at When this snow report was last updated.
     *
     * @return self
     */
    public function setReportedAt($reported_at)
    {
        if (is_null($reported_at)) {
            throw new \InvalidArgumentException('non-nullable reported_at cannot be null');
        }
        $this->container['reported_at'] = $reported_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


