<?php
/**
 * SurfaceCondition
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;
use \MtnManager\ObjectSerializer;

/**
 * SurfaceCondition Class Doc Comment
 *
 * @category Class
 * @description Industry-standard letter codes describing snow surface conditions.
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SurfaceCondition
{
    /**
     * Possible values of this enum
     */
    public const BS = 'BS';

    public const CO = 'CO';

    public const FG = 'FG';

    public const HP = 'HP';

    public const IP = 'IP';

    public const IS = 'IS';

    public const LG = 'LG';

    public const MG = 'MG';

    public const P = 'P';

    public const PP = 'PP';

    public const SC = 'SC';

    public const TC = 'TC';

    public const V = 'V';

    public const WG = 'WG';

    public const WP = 'WP';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BS,
            self::CO,
            self::FG,
            self::HP,
            self::IP,
            self::IS,
            self::LG,
            self::MG,
            self::P,
            self::PP,
            self::SC,
            self::TC,
            self::V,
            self::WG,
            self::WP
        ];
    }
}


