<?php
/**
 * WeatherConditionCode
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;
use \MtnManager\ObjectSerializer;

/**
 * WeatherConditionCode Class Doc Comment
 *
 * @category Class
 * @description Weather condition code   Variants mirror Apple&#39;s &#x60;WeatherCondition&#x60; enum exactly so they match the  &#x60;conditionCode&#x60; strings returned by the WeatherKit REST API verbatim.  See https://developer.apple.com/documentation/weatherkit/weathercondition
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WeatherConditionCode
{
    /**
     * Possible values of this enum
     */
    public const CLEAR = 'Clear';

    public const CLOUDY = 'Cloudy';

    public const FOGGY = 'Foggy';

    public const HAZE = 'Haze';

    public const MOSTLY_CLEAR = 'MostlyClear';

    public const MOSTLY_CLOUDY = 'MostlyCloudy';

    public const PARTLY_CLOUDY = 'PartlyCloudy';

    public const SMOKY = 'Smoky';

    public const BLOWING_DUST = 'BlowingDust';

    public const BREEZY = 'Breezy';

    public const WINDY = 'Windy';

    public const DRIZZLE = 'Drizzle';

    public const HEAVY_RAIN = 'HeavyRain';

    public const ISOLATED_THUNDERSTORMS = 'IsolatedThunderstorms';

    public const RAIN = 'Rain';

    public const SUN_SHOWERS = 'SunShowers';

    public const SCATTERED_THUNDERSTORMS = 'ScatteredThunderstorms';

    public const STRONG_STORMS = 'StrongStorms';

    public const THUNDERSTORMS = 'Thunderstorms';

    public const FRIGID = 'Frigid';

    public const HAIL = 'Hail';

    public const HOT = 'Hot';

    public const FLURRIES = 'Flurries';

    public const SLEET = 'Sleet';

    public const SNOW = 'Snow';

    public const SUN_FLURRIES = 'SunFlurries';

    public const WINTRY_MIX = 'WintryMix';

    public const BLIZZARD = 'Blizzard';

    public const BLOWING_SNOW = 'BlowingSnow';

    public const FREEZING_DRIZZLE = 'FreezingDrizzle';

    public const FREEZING_RAIN = 'FreezingRain';

    public const HEAVY_SNOW = 'HeavySnow';

    public const HURRICANE = 'Hurricane';

    public const TROPICAL_STORM = 'TropicalStorm';

    public const UNKNOWN = 'Unknown';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CLEAR,
            self::CLOUDY,
            self::FOGGY,
            self::HAZE,
            self::MOSTLY_CLEAR,
            self::MOSTLY_CLOUDY,
            self::PARTLY_CLOUDY,
            self::SMOKY,
            self::BLOWING_DUST,
            self::BREEZY,
            self::WINDY,
            self::DRIZZLE,
            self::HEAVY_RAIN,
            self::ISOLATED_THUNDERSTORMS,
            self::RAIN,
            self::SUN_SHOWERS,
            self::SCATTERED_THUNDERSTORMS,
            self::STRONG_STORMS,
            self::THUNDERSTORMS,
            self::FRIGID,
            self::HAIL,
            self::HOT,
            self::FLURRIES,
            self::SLEET,
            self::SNOW,
            self::SUN_FLURRIES,
            self::WINTRY_MIX,
            self::BLIZZARD,
            self::BLOWING_SNOW,
            self::FREEZING_DRIZZLE,
            self::FREEZING_RAIN,
            self::HEAVY_SNOW,
            self::HURRICANE,
            self::TROPICAL_STORM,
            self::UNKNOWN
        ];
    }
}


