<?php
/**
 * Webcam
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MtnManager\Model;

use \ArrayAccess;
use \MtnManager\ObjectSerializer;

/**
 * Webcam Class Doc Comment
 *
 * @category Class
 * @description A public webcam entry. Consumers pick &#x60;latest&#x60; (always the newest frame) or  &#x60;latest-daylight&#x60; (the last daylight frame, never a black night shot)  depending on whether they want the freshest or a guaranteed-lit image.
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Webcam implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Webcam';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'uuid' => 'string',
        'name' => 'string',
        'area_uuid' => 'string',
        'area_name' => 'string',
        'area_display_order' => 'int',
        'latest_image_url' => 'string',
        'latest_daylight_image_url' => 'string',
        'latest_thumb_url' => 'string',
        'latest_daylight_thumb_url' => 'string',
        'last_frame_at' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'uuid' => null,
        'name' => null,
        'area_uuid' => null,
        'area_name' => null,
        'area_display_order' => 'int32',
        'latest_image_url' => null,
        'latest_daylight_image_url' => null,
        'latest_thumb_url' => null,
        'latest_daylight_thumb_url' => null,
        'last_frame_at' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'uuid' => false,
        'name' => false,
        'area_uuid' => true,
        'area_name' => true,
        'area_display_order' => true,
        'latest_image_url' => false,
        'latest_daylight_image_url' => false,
        'latest_thumb_url' => false,
        'latest_daylight_thumb_url' => false,
        'last_frame_at' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'name' => 'name',
        'area_uuid' => 'area_uuid',
        'area_name' => 'area_name',
        'area_display_order' => 'area_display_order',
        'latest_image_url' => 'latest_image_url',
        'latest_daylight_image_url' => 'latest_daylight_image_url',
        'latest_thumb_url' => 'latest_thumb_url',
        'latest_daylight_thumb_url' => 'latest_daylight_thumb_url',
        'last_frame_at' => 'last_frame_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'name' => 'setName',
        'area_uuid' => 'setAreaUuid',
        'area_name' => 'setAreaName',
        'area_display_order' => 'setAreaDisplayOrder',
        'latest_image_url' => 'setLatestImageUrl',
        'latest_daylight_image_url' => 'setLatestDaylightImageUrl',
        'latest_thumb_url' => 'setLatestThumbUrl',
        'latest_daylight_thumb_url' => 'setLatestDaylightThumbUrl',
        'last_frame_at' => 'setLastFrameAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'name' => 'getName',
        'area_uuid' => 'getAreaUuid',
        'area_name' => 'getAreaName',
        'area_display_order' => 'getAreaDisplayOrder',
        'latest_image_url' => 'getLatestImageUrl',
        'latest_daylight_image_url' => 'getLatestDaylightImageUrl',
        'latest_thumb_url' => 'getLatestThumbUrl',
        'latest_daylight_thumb_url' => 'getLatestDaylightThumbUrl',
        'last_frame_at' => 'getLastFrameAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('area_uuid', $data ?? [], null);
        $this->setIfExists('area_name', $data ?? [], null);
        $this->setIfExists('area_display_order', $data ?? [], null);
        $this->setIfExists('latest_image_url', $data ?? [], null);
        $this->setIfExists('latest_daylight_image_url', $data ?? [], null);
        $this->setIfExists('latest_thumb_url', $data ?? [], null);
        $this->setIfExists('latest_daylight_thumb_url', $data ?? [], null);
        $this->setIfExists('last_frame_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid'] === null) {
            $invalidProperties[] = "'uuid' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['latest_image_url'] === null) {
            $invalidProperties[] = "'latest_image_url' can't be null";
        }
        if ($this->container['latest_daylight_image_url'] === null) {
            $invalidProperties[] = "'latest_daylight_image_url' can't be null";
        }
        if ($this->container['latest_thumb_url'] === null) {
            $invalidProperties[] = "'latest_thumb_url' can't be null";
        }
        if ($this->container['latest_daylight_thumb_url'] === null) {
            $invalidProperties[] = "'latest_daylight_thumb_url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string $uuid uuid
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets area_uuid
     *
     * @return string|null
     */
    public function getAreaUuid()
    {
        return $this->container['area_uuid'];
    }

    /**
     * Sets area_uuid
     *
     * @param string|null $area_uuid area_uuid
     *
     * @return self
     */
    public function setAreaUuid($area_uuid)
    {
        if (is_null($area_uuid)) {
            array_push($this->openAPINullablesSetToNull, 'area_uuid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_uuid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_uuid'] = $area_uuid;

        return $this;
    }

    /**
     * Gets area_name
     *
     * @return string|null
     */
    public function getAreaName()
    {
        return $this->container['area_name'];
    }

    /**
     * Sets area_name
     *
     * @param string|null $area_name area_name
     *
     * @return self
     */
    public function setAreaName($area_name)
    {
        if (is_null($area_name)) {
            array_push($this->openAPINullablesSetToNull, 'area_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_name'] = $area_name;

        return $this;
    }

    /**
     * Gets area_display_order
     *
     * @return int|null
     */
    public function getAreaDisplayOrder()
    {
        return $this->container['area_display_order'];
    }

    /**
     * Sets area_display_order
     *
     * @param int|null $area_display_order area_display_order
     *
     * @return self
     */
    public function setAreaDisplayOrder($area_display_order)
    {
        if (is_null($area_display_order)) {
            array_push($this->openAPINullablesSetToNull, 'area_display_order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('area_display_order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['area_display_order'] = $area_display_order;

        return $this;
    }

    /**
     * Gets latest_image_url
     *
     * @return string
     */
    public function getLatestImageUrl()
    {
        return $this->container['latest_image_url'];
    }

    /**
     * Sets latest_image_url
     *
     * @param string $latest_image_url URL of the newest frame (refreshes within ~60s via the edge cache).
     *
     * @return self
     */
    public function setLatestImageUrl($latest_image_url)
    {
        if (is_null($latest_image_url)) {
            throw new \InvalidArgumentException('non-nullable latest_image_url cannot be null');
        }
        $this->container['latest_image_url'] = $latest_image_url;

        return $this;
    }

    /**
     * Gets latest_daylight_image_url
     *
     * @return string
     */
    public function getLatestDaylightImageUrl()
    {
        return $this->container['latest_daylight_image_url'];
    }

    /**
     * Sets latest_daylight_image_url
     *
     * @param string $latest_daylight_image_url URL of the last daylight frame.
     *
     * @return self
     */
    public function setLatestDaylightImageUrl($latest_daylight_image_url)
    {
        if (is_null($latest_daylight_image_url)) {
            throw new \InvalidArgumentException('non-nullable latest_daylight_image_url cannot be null');
        }
        $this->container['latest_daylight_image_url'] = $latest_daylight_image_url;

        return $this;
    }

    /**
     * Gets latest_thumb_url
     *
     * @return string
     */
    public function getLatestThumbUrl()
    {
        return $this->container['latest_thumb_url'];
    }

    /**
     * Sets latest_thumb_url
     *
     * @param string $latest_thumb_url latest_thumb_url
     *
     * @return self
     */
    public function setLatestThumbUrl($latest_thumb_url)
    {
        if (is_null($latest_thumb_url)) {
            throw new \InvalidArgumentException('non-nullable latest_thumb_url cannot be null');
        }
        $this->container['latest_thumb_url'] = $latest_thumb_url;

        return $this;
    }

    /**
     * Gets latest_daylight_thumb_url
     *
     * @return string
     */
    public function getLatestDaylightThumbUrl()
    {
        return $this->container['latest_daylight_thumb_url'];
    }

    /**
     * Sets latest_daylight_thumb_url
     *
     * @param string $latest_daylight_thumb_url latest_daylight_thumb_url
     *
     * @return self
     */
    public function setLatestDaylightThumbUrl($latest_daylight_thumb_url)
    {
        if (is_null($latest_daylight_thumb_url)) {
            throw new \InvalidArgumentException('non-nullable latest_daylight_thumb_url cannot be null');
        }
        $this->container['latest_daylight_thumb_url'] = $latest_daylight_thumb_url;

        return $this;
    }

    /**
     * Gets last_frame_at
     *
     * @return string|null
     */
    public function getLastFrameAt()
    {
        return $this->container['last_frame_at'];
    }

    /**
     * Sets last_frame_at
     *
     * @param string|null $last_frame_at Time of the most recently published frame; omitted until the first frame.
     *
     * @return self
     */
    public function setLastFrameAt($last_frame_at)
    {
        if (is_null($last_frame_at)) {
            array_push($this->openAPINullablesSetToNull, 'last_frame_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_frame_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_frame_at'] = $last_frame_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


