<?php
/**
 * OverviewTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MtnManager\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OverviewTest Class Doc Comment
 *
 * @category    Class
 * @description Provides a snapshot of the resort&#39;s current operational state including  today&#39;s scheduled hours (calculated from operating hour rules), run/lift  overview counts, the current season, and written news.
 * @package     MtnManager
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OverviewTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Overview"
     */
    public function testOverview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "opens_at"
     */
    public function testPropertyOpensAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "closes_at"
     */
    public function testPropertyClosesAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "season"
     */
    public function testPropertySeason()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "news"
     */
    public function testPropertyNews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "news_html"
     */
    public function testPropertyNewsHtml()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "news_updated_at"
     */
    public function testPropertyNewsUpdatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "open_runs"
     */
    public function testPropertyOpenRuns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "groomed_runs"
     */
    public function testPropertyGroomedRuns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_runs"
     */
    public function testPropertyTotalRuns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "runs_updated_at"
     */
    public function testPropertyRunsUpdatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "open_lifts"
     */
    public function testPropertyOpenLifts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_lifts"
     */
    public function testPropertyTotalLifts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lifts_updated_at"
     */
    public function testPropertyLiftsUpdatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "open_summer_trails"
     */
    public function testPropertyOpenSummerTrails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_summer_trails"
     */
    public function testPropertyTotalSummerTrails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "summer_trails_updated_at"
     */
    public function testPropertySummerTrailsUpdatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "open_terrain_parks"
     */
    public function testPropertyOpenTerrainParks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_terrain_parks"
     */
    public function testPropertyTotalTerrainParks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "terrain_parks_updated_at"
     */
    public function testPropertyTerrainParksUpdatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
