<?php
/**
 * PointMarkerOneOf2Test
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MtnManager\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PointMarkerOneOf2Test Class Doc Comment
 *
 * @category    Class
 * @description PointMarkerOneOf2
 * @package     MtnManager
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PointMarkerOneOf2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PointMarkerOneOf2"
     */
    public function testPointMarkerOneOf2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "icon"
     */
    public function testPropertyIcon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "searchable"
     */
    public function testPropertySearchable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
