<?php
/**
 * MtnManagerApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MtnManager API
 *
 * The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mtnmanager.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MtnManager\Test\Api;

use \MtnManager\Configuration;
use \MtnManager\ApiException;
use \MtnManager\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MtnManagerApiTest Class Doc Comment
 *
 * @category Class
 * @package  MtnManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MtnManagerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getFullReport
     *
     * Get full report.
     *
     */
    public function testGetFullReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getHours
     *
     * Get operating hours.
     *
     */
    public function testGetHours()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLifts
     *
     * Get lifts.
     *
     */
    public function testGetLifts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOverview
     *
     * Get overview.
     *
     */
    public function testGetOverview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRuns
     *
     * Get runs.
     *
     */
    public function testGetRuns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSnow
     *
     * Get snow conditions.
     *
     */
    public function testGetSnow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSummerTrails
     *
     * Get summer trails.
     *
     */
    public function testGetSummerTrails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTerrainParks
     *
     * Get terrain parks.
     *
     */
    public function testGetTerrainParks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWeather
     *
     * Get weather.
     *
     */
    public function testGetWeather()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
